# Generated by Django 5.1.7 on 2025-04-02 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_products_quantity_alter_products_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='discount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=7, verbose_name='Скидка в %'),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.DecimalField(decimal_places=0, default='нет в наличии', max_digits=7, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='products',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Количество'),
        ),
    ]
