# Generated by Django 5.1.7 on 2025-04-06 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_color_flowertype_height_alter_categories_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Color',
        ),
        migrations.DeleteModel(
            name='FlowerType',
        ),
        migrations.DeleteModel(
            name='Height',
        ),
    ]
