# Generated by Django 5.1.7 on 2025-04-10 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0007_delete_color_delete_flowertype_delete_height'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='structure',
            field=models.CharField(blank=True, max_length=300, null=True, unique=True, verbose_name='Состав'),
        ),
    ]
